### ISSUE TITLE
ReferenceError in measure.js

### ISSUE THREAD

**Issue by jlcx** [google/abstracttext#25]
I'm not sure yet why `measure.js` is running into an issue on one of my systems, but it does seem like [line 153](https://github.com/google/abstracttext/blob/ca6eb8db4a5e49d30af5b2faff093dd856eb599b/eneyj/src/scripts/measure.js#L153) is referencing something that hasn't been defined.

```
Z157
Z157T1 Z157C1 1 ms (Ø 0 ms in 0 runs)
Z157T1 Z157C2 18 ms (Ø 0 ms in 0 runs)
Z157 Z157T1 Z157C2
/home/jamie/src/abstracttext/eneyj/src/scripts/measure.js:153
        console.log(write(call))
                          ^

ReferenceError: call is not defined
    at Object.<anonymous> (/home/jamie/src/abstracttext/eneyj/src/scripts/measure.js:153:27)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by arthurpsmith** [comment]
@jlcx can you post your config/system.json file so we can check node versions etc? This all works fine for me; if you run the docker instance it should work and runs automatically.

Line 153 may be a mistake; it's only supposed to be called when one of the tests fails, so the main question here is probably why one of your tests failed?

**Comment by jlcx** [comment]
After poking around a bit, I think the tests failed because the system they failed on is an Arch-based system, where `python` refers to Python 3, meaning that the Python division tests return a `float` instead of an `int` (except on division by zero, where the tests still pass). 

```
{
  "arch": "x64",
  "cpus": 16,
  "cpu_zero": "Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz",
  "platform": "linux",
  "os_release": "5.6.16-1-MANJARO",
  "os_type": "Linux",
  "node_version": "v14.3.0"
}% 
```

Commenting out line 153, these are the failures I see:

```
Z157 Z157T2 Z157C2
Actual  : Z5(Z410, "[{\"keyword\":\"pattern\",\"dataPath\":\".Z70K1\",\"schemaPath\":\"#/properties/Z70K1/pattern\",\"params\":{\"pattern\":\"^[0-9]+$\"},\"message\":\"should match pattern \\\"^[0-9]+$\\\"\"}]", "val")
Expected: Z70("1")

Z157T2 Z157C3 0 ms (Ø 0 ms in 0 runs)
Z157T3 Z157C1 522 ms (Ø 0 ms in 0 runs)
Z157T3 Z157C2 16 ms (Ø 0 ms in 0 runs)
Z157 Z157T3 Z157C2
Actual  : Z5(Z410, "[{\"keyword\":\"pattern\",\"dataPath\":\".Z70K1\",\"schemaPath\":\"#/properties/Z70K1/pattern\",\"params\":{\"pattern\":\"^[0-9]+$\"},\"message\":\"should match pattern \\\"^[0-9]+$\\\"\"}]", "val")
Expected: Z70("1")

Z157T3 Z157C3 0 ms (Ø 0 ms in 0 runs)
Z157T4 Z157C1 528 ms (Ø 0 ms in 0 runs)
Z157T4 Z157C2 17 ms (Ø 0 ms in 0 runs)
Z157 Z157T4 Z157C2
Actual  : Z5(Z410, "[{\"keyword\":\"pattern\",\"dataPath\":\".Z70K1\",\"schemaPath\":\"#/properties/Z70K1/pattern\",\"params\":{\"pattern\":\"^[0-9]+$\"},\"message\":\"should match pattern \\\"^[0-9]+$\\\"\"}]", "val")
Expected: Z70("2")

Z157T4 Z157C3 0 ms (Ø 0 ms in 0 runs)
Z157T5 Z157C1 547 ms (Ø 0 ms in 0 runs)
Z157T5 Z157C2 16 ms (Ø 0 ms in 0 runs)
Z157 Z157T5 Z157C2
Actual  : Z5(Z410, "[{\"keyword\":\"pattern\",\"dataPath\":\".Z70K1\",\"schemaPath\":\"#/properties/Z70K1/pattern\",\"params\":{\"pattern\":\"^[0-9]+$\"},\"message\":\"should match pattern \\\"^[0-9]+$\\\"\"}]", "val")
Expected: Z70("3")

Z157T5 Z157C3 1 ms (Ø 0 ms in 0 runs)
Z157T6 Z157C1 625 ms (Ø 0 ms in 0 runs)
Z157T6 Z157C2 16 ms (Ø 0 ms in 0 runs)
Z157 Z157T6 Z157C2
Actual  : Z5(Z410, "[{\"keyword\":\"pattern\",\"dataPath\":\".Z70K1\",\"schemaPath\":\"#/properties/Z70K1/pattern\",\"params\":{\"pattern\":\"^[0-9]+$\"},\"message\":\"should match pattern \\\"^[0-9]+$\\\"\"}]", "val")
Expected: Z70("7")

Z157T6 Z157C3 0 ms (Ø 0 ms in 0 runs)
Z157T7 Z157C1 1 ms (Ø 0 ms in 0 runs)
Z157T7 Z157C2 18 ms (Ø 0 ms in 0 runs)
Z157T7 Z157C3 0 ms (Ø 0 ms in 0 runs)
Z157T8 Z157C1 1 ms (Ø 0 ms in 0 runs)
Z157T8 Z157C2 18 ms (Ø 0 ms in 0 runs)
Z157 Z157T8 Z157C2
Actual  : Z5(Z410, "[{\"keyword\":\"pattern\",\"dataPath\":\".Z70K1\",\"schemaPath\":\"#/properties/Z70K1/pattern\",\"params\":{\"pattern\":\"^[0-9]+$\"},\"message\":\"should match pattern \\\"^[0-9]+$\\\"\"}]", "val")
Expected: Z70("0")

```

**Comment by arthurpsmith** [comment]
Ooh, we really should work with python3, not rely on python2 here! That's interesting at least though...
